--- OKF (Open Knowledge Format) frontmatter utilities
--- Inserts OKF-compliant YAML frontmatter at the top of markdown files.
---
--- Spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
---
--- Frontmatter fields (v0.1):
---   type (REQUIRED) — concept kind: "Playbook", "Process", "Reference", "Metric", etc.
---   title (recommended) — human-readable display name
---   description (recommended) — one-line summary
---   tags (optional) — list of short strings
---   timestamp (optional) — ISO 8601 datetime, auto-filled
---   resource (optional) — canonical URI for the underlying asset
---
--- Usage:
---   require("utils.okf").insert_frontmatter()           -- uses defaults
---   require("utils.okf").insert_frontmatter({           -- custom defaults
---     type = "Playbook",
---     title = "My Concept",
---   })
local M = {}

--- Default OKF frontmatter values
M.defaults = {
  type = "Concept",
  title = "",
  description = "",
  tags = {},
  timestamp = true, -- auto-generate ISO 8601 timestamp
  resource = "",
}

--- Generate an ISO 8601 UTC timestamp string
---@return string
local function iso8601_timestamp()
  return os.date "%Y-%m-%dT%H:%M:%SZ"
end

--- Derive a title from the current buffer's filename (title-case, no extension)
---@return string
local function title_from_filename()
  local bufname = vim.api.nvim_buf_get_name(0)
  if not bufname or bufname == "" then
    return ""
  end
  local basename = vim.fn.fnamemodify(bufname, ":t:r") -- filename without extension
  -- Convert kebab-case or snake_case to Title Case
  local title = basename:gsub("[-_]", " "):gsub("^%l", string.upper)
  return title
end

--- Check if the buffer already has YAML frontmatter
---@return boolean
local function has_frontmatter()
  if vim.api.nvim_get_current_line() ~= "---" then
    return false
  end
  local second_line = vim.api.nvim_buf_get_lines(0, 1, 2, false)[1] or ""
  return second_line ~= "---" -- ---\n--- is not valid frontmatter (empty)
end

--- Format a YAML frontmatter block from config
---@param config table
---@return string
local function format_frontmatter(config)
  local lines = { "---" }

  -- type is required
  table.insert(lines, 'type: "' .. config.type .. '"')

  -- title (recommended)
  if config.title and config.title ~= "" then
    table.insert(lines, 'title: "' .. config.title .. '"')
  end

  -- description (recommended)
  if config.description and config.description ~= "" then
    table.insert(lines, 'description: "' .. config.description .. '"')
  end

  -- tags (optional)
  if config.tags and #config.tags > 0 then
    table.insert(lines, "tags:")
    for _, tag in ipairs(config.tags) do
      table.insert(lines, "  - " .. tag)
    end
  end

  -- timestamp (optional, auto-generated by default)
  if config.timestamp == true then
    table.insert(lines, 'timestamp: "' .. iso8601_timestamp() .. '"')
  elseif config.timestamp and config.timestamp ~= "" then
    table.insert(lines, 'timestamp: "' .. config.timestamp .. '"')
  end

  -- resource (optional)
  if config.resource and config.resource ~= "" then
    table.insert(lines, 'resource: "' .. config.resource .. '"')
  end

  table.insert(lines, "---")
  return table.concat(lines, "\n")
end

--- Insert OKF frontmatter at the top of the current buffer
---@param opts? table Optional overrides for defaults
M.insert_frontmatter = function(opts)
  if has_frontmatter() then
    vim.notify("OKF: Buffer already has frontmatter", vim.log.levels.WARN)
    return
  end

  local config = vim.tbl_deep_extend("force", {}, M.defaults, opts or {})

  -- Auto-derive title from filename if not provided
  if not config.title or config.title == "" then
    config.title = title_from_filename()
  end

  local frontmatter = format_frontmatter(config)
  local cursor_pos = vim.api.nvim_win_get_cursor(0)

  -- Insert at the top of the file
  vim.api.nvim_buf_set_lines(0, 0, 0, false, { frontmatter .. "\n" })

  -- Restore cursor position (offset by the number of inserted lines)
  local num_inserted = vim.split(frontmatter, "\n")
  vim.api.nvim_win_set_cursor(0, { cursor_pos[1] + #num_inserted, cursor_pos[2] })

  vim.notify("OKF: Frontmatter inserted (type: " .. config.type .. ")", vim.log.levels.INFO)
end

--- Update the timestamp field in existing frontmatter to current time
M.update_timestamp = function()
  local lines = vim.api.nvim_buf_get_lines(0, 0, -1, false)
  if lines[1] ~= "---" then
    vim.notify("OKF: No frontmatter found", vim.log.levels.WARN)
    return
  end

  for i, line in ipairs(lines) do
    if line:match("^timestamp:") then
      lines[i] = 'timestamp: "' .. iso8601_timestamp() .. '"'
      vim.api.nvim_buf_set_lines(0, 0, #lines, false, lines)
      vim.notify("OKF: Timestamp updated to " .. iso8601_timestamp(), vim.log.levels.INFO)
      return
    end
  end

  vim.notify("OKF: No timestamp field found in frontmatter", vim.log.levels.WARN)
end

return M
